# Generated by Django 2.2.19 on 2021-03-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('sinopse', models.TextField(max_length=1000, verbose_name='Sinopse')),
                ('trailer', models.URLField(blank=True, null=True, verbose_name='Trailer')),
                ('dataEstreia', models.DateField(blank=True, help_text='Use este formato: DD/MM/AAAA', null=True, verbose_name='Data de Estreia')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
            },
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(help_text='Digite sem pontos e traços.', max_length=11, unique=True, verbose_name='CPF'),
        ),
    ]
