# Generated by Django 2.2.19 on 2021-06-07 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20210530_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filme',
            options={'ordering': ['id'], 'verbose_name': 'Filme', 'verbose_name_plural': 'Filmes'},
        ),
    ]
