# Generated by Django 2.2.19 on 2021-06-08 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20210607_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessao',
            options={'ordering': ['id'], 'verbose_name': 'Sessão', 'verbose_name_plural': 'Sessões'},
        ),
    ]
