# Generated by Django 2.2.19 on 2021-06-08 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20210607_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='application.Filme'),
        ),
    ]
