# Generated by Django 2.2.19 on 2021-06-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20210607_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='assentos',
            field=models.ManyToManyField(to='application.Assento'),
        ),
    ]
