# Generated by Django 2.2.19 on 2021-06-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_sessao_assentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assento',
            name='disponibilidade',
        ),
    ]
